http:
   port: "8081"
   
log:
  message: "welcome to CI/CD Process here we are learning cicd process"
  
deployment:
     app:
       runtime: "3.2.0"
     region: "us-east-2"
     workers: "1"
     workersType: "MICRO"
     
other: "123"